# Generated by Django 4.2.5 on 2023-09-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('product', models.CharField(max_length=500)),
                ('productlocation', models.CharField(max_length=500)),
                ('pickoutlocation', models.CharField(max_length=500)),
                ('pickupdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='serviceproductcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('productlocation', models.CharField(max_length=500)),
                ('pickoutlocation', models.CharField(max_length=500)),
                ('pickupdate', models.DateField(null=True)),
                ('issueofproduct', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='paymentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('product', models.CharField(max_length=500)),
                ('productlocation', models.CharField(max_length=500)),
                ('pickoutlocation', models.CharField(max_length=500)),
                ('pickupdate', models.DateField(null=True)),
                ('pickoutdate', models.DateField(null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.serviceamount')),
            ],
        ),
    ]
