# Generated by Django 4.2.5 on 2023-09-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=500)),
                ('shoplocation', models.CharField(max_length=500)),
                ('phone', models.ImageField(upload_to='')),
                ('duration', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='serviceproductcollection',
            old_name='pickoutlocation',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='serviceproductcollection',
            name='pickupdate',
        ),
    ]
